version: '3.8'

services:
 dbcideca:
    image: aagudelom/dbcideca:1.0.0-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile.mongo    
    container_name: dbcideca
    volumes:      
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      - mongodb_log:/data/log
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - DB_NAME=$DB_DATA_NAME
      - DB_USER=$DB_NAME_USER
      - DB_PASS=$DB_PASS_USER
    ports:
      - 27017:27017    
    networks:
      app-network:
        aliases:
          - "hostdb"      
    command: ['--config', '/data/configdb/mongod.conf']
volumes:
 mongodb:
 mongodb_config:
 mongodb_log:
networks:
 app-network:
  driver: bridge