version: '3.8'

services:
 web:
  image: webcideca
  container_name: webcideca
  working_dir: ${HOME_FOLDER}  
  build:
   context: .
   dockerfile: Dockerfile
   #args:   
  env_file: .env
  ports:
   - 80:3000
  environment:
   - NODE_ENV=production
   - PORT=3000
  volumes:
   - .:$HOME_FOLDER
   - node_modules:$HOME_FOLDER/node_modules
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 15M
    restart_policy:
      condition: on-failure
  command: node server.js
  networks:
      - app-network
volumes:
  node_modules:
networks:
  app-network:
    driver: bridge