version: '3.8'

services:
 mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGODB_USERNAME=$MONGO_US
      - MONGODB_PASSWORD=$MONGO_PS
      - MONGODB_DATABASE=$MONGO_DB
    command: /docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - 27017:27017
    networks:
      app-network:
        aliases:
          - "mongo_db"
          - "mongo_server"        
volumes:
 mongodb:
 mongodb_config:   
networks:
 app-network:
  driver: bridge