FROM mongo:latest
ENV MONGO_FOLDER_LOG=/data/log
ENV MONGO_FOLDER_CNF=/data/configdb

RUN mkdir -p ${MONGO_FOLDER_LOG}
RUN chmod a+rw ${MONGO_FOLDER_LOG}

RUN touch ${MONGO_FOLDER_LOG}/mongod.log
RUN chmod a+rw ${MONGO_FOLDER_LOG}/mongod.log

RUN mkdir -p ${MONGO_FOLDER_CNF}
ADD "mongod.conf" ${MONGO_FOLDER_CNF} 
RUN chmod a+r ${MONGO_FOLDER_CNF}/mongod.conf