version: '3.8'

services:
 mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo    
    container_name: mongodb
    volumes:      
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      - mongodb_log:/data/log
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD          
    ports:
      - 27017:27017
    networks:
      app-network:
        aliases:
          - "hostdb"      
    command: mongod --config /data/configdb/mongod.conf
volumes:
 mongodb:
 mongodb_config:
 mongodb_log:
networks:
 app-network:
  driver: bridge